"""
Rootsy — Curated plant database.

50 common garden plants, hand-curated with sensible cycle / watering / sunlight /
companion data. At seed time, seed_plants.py resolves `wiki_title` to a real
image URL via Wikipedia's REST API, guaranteeing each plant gets a unique photo.

Fields map 1:1 to the `plants` table (see supabase_schema.sql).
`wiki_title` is seed-only; it's dropped before the row is inserted.
"""

# Sunlight: ["full sun"] = 6+ hrs direct, ["part sun"] = 3-6 hrs, ["part shade"] = <3 hrs
# Watering: "Minimum" | "Average" | "Frequent"
# Cycle:    "annual" | "biennial" | "perennial"
# Growth rate: "Slow" | "Medium" | "Fast"
# Care level:  "Easy" | "Moderate" | "Difficult"

PLANTS: list[dict] = [
    # ---------------- Fruiting vegetables ----------------
    {
        "wiki_title": "Tomato",
        "common_name": "Tomato",
        "scientific_name": "Solanum lycopersicum",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Moderate",
        "description": "Warm-season staple grown for its juicy red fruit. Stake or cage indeterminate varieties; feed regularly and water deeply at the base to avoid leaf disease.",
        "harvest_days_min": 60,
        "harvest_days_max": 85,
        "companions": ["basil", "parsley", "carrot", "onion", "garlic", "chive", "lettuce"],
        "avoid_near": ["cabbage", "broccoli", "cauliflower", "potato", "fennel", "corn"],
    },
    {
        "wiki_title": "Cherry_tomato",
        "common_name": "Cherry Tomato",
        "scientific_name": "Solanum lycopersicum var. cerasiforme",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Small-fruited, prolific tomato perfect for containers and snacking. Ripens earlier than full-size tomatoes and keeps producing until frost.",
        "harvest_days_min": 55,
        "harvest_days_max": 75,
        "companions": ["basil", "parsley", "carrot", "onion", "garlic", "chive", "lettuce"],
        "avoid_near": ["cabbage", "broccoli", "cauliflower", "potato", "fennel", "corn"],
    },
    {
        "wiki_title": "Cucumber",
        "common_name": "Cucumber",
        "scientific_name": "Cucumis sativus",
        "family": "Cucurbitaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Vining warm-season crop producing crisp green fruit. Train on a trellis for straighter cucumbers and easier harvesting.",
        "harvest_days_min": 50,
        "harvest_days_max": 70,
        "companions": ["bean", "corn", "dill", "pea", "radish", "lettuce"],
        "avoid_near": ["potato", "sage", "melon"],
    },
    {
        "wiki_title": "Zucchini",
        "common_name": "Zucchini",
        "scientific_name": "Cucurbita pepo",
        "family": "Cucurbitaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Bush-type summer squash that produces abundantly. Harvest young (15-20 cm) for the best flavor and to keep the plant producing.",
        "harvest_days_min": 45,
        "harvest_days_max": 60,
        "companions": ["corn", "bean", "nasturtium", "radish"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Bell_pepper",
        "common_name": "Bell Pepper",
        "scientific_name": "Capsicum annuum",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "Warm-season sweet pepper. Start indoors 8 weeks before last frost. Fruit ripens from green to red, yellow, or orange.",
        "harvest_days_min": 65,
        "harvest_days_max": 85,
        "companions": ["basil", "onion", "carrot", "tomato"],
        "avoid_near": ["bean", "fennel"],
    },
    {
        "wiki_title": "Chili_pepper",
        "common_name": "Chili Pepper",
        "scientific_name": "Capsicum annuum",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "Hot pepper cultivars range from mild to fiery. Needs a long warm season and consistent watering to avoid blossom-end rot.",
        "harvest_days_min": 70,
        "harvest_days_max": 90,
        "companions": ["basil", "onion", "carrot", "tomato"],
        "avoid_near": ["bean", "fennel"],
    },
    {
        "wiki_title": "Eggplant",
        "common_name": "Eggplant",
        "scientific_name": "Solanum melongena",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "Heat-loving nightshade producing glossy purple fruit. Stake plants as fruit matures and harvest when skin is shiny.",
        "harvest_days_min": 80,
        "harvest_days_max": 100,
        "companions": ["bean", "pepper", "spinach", "marigold"],
        "avoid_near": ["fennel"],
    },

    # ---------------- Leafy greens ----------------
    {
        "wiki_title": "Lettuce",
        "common_name": "Lettuce",
        "scientific_name": "Lactuca sativa",
        "family": "Asteraceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Frequent",
        "sunlight": ["part sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Cool-season leafy green. Sow every 2 weeks for a continuous harvest; bolts quickly once temperatures climb past 24 °C.",
        "harvest_days_min": 30,
        "harvest_days_max": 60,
        "companions": ["carrot", "radish", "strawberry", "cucumber", "onion"],
        "avoid_near": ["parsley"],
    },
    {
        "wiki_title": "Spinach",
        "common_name": "Spinach",
        "scientific_name": "Spinacia oleracea",
        "family": "Amaranthaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Cold-hardy leafy green rich in iron. Plant in early spring or autumn; hot weather causes rapid bolting.",
        "harvest_days_min": 40,
        "harvest_days_max": 50,
        "companions": ["strawberry", "pea", "bean", "cabbage", "cauliflower"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Kale",
        "common_name": "Kale",
        "scientific_name": "Brassica oleracea var. sabellica",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Hardy brassica that sweetens after frost. Pick outer leaves as the plant grows for repeated harvests over many months.",
        "harvest_days_min": 55,
        "harvest_days_max": 75,
        "companions": ["onion", "beet", "celery", "potato"],
        "avoid_near": ["tomato", "strawberry", "bean"],
    },
    {
        "wiki_title": "Chard",
        "common_name": "Swiss Chard",
        "scientific_name": "Beta vulgaris subsp. cicla",
        "family": "Amaranthaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Colorful leafy green with edible stems. Tolerates heat better than spinach and crops from spring through autumn.",
        "harvest_days_min": 50,
        "harvest_days_max": 60,
        "companions": ["bean", "onion", "cabbage"],
        "avoid_near": ["corn"],
    },
    {
        "wiki_title": "Eruca_vesicaria",
        "common_name": "Arugula",
        "scientific_name": "Eruca vesicaria",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Peppery salad green, ready in just a few weeks. Cool-season crop that bolts quickly in heat but can be resown often.",
        "harvest_days_min": 30,
        "harvest_days_max": 40,
        "companions": ["lettuce", "carrot", "onion"],
        "avoid_near": [],
    },

    # ---------------- Brassicas ----------------
    {
        "wiki_title": "Broccoli",
        "common_name": "Broccoli",
        "scientific_name": "Brassica oleracea var. italica",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "Cool-season head-forming brassica. Harvest the central head before buds open; side shoots will continue producing for weeks.",
        "harvest_days_min": 60,
        "harvest_days_max": 85,
        "companions": ["onion", "garlic", "celery", "chamomile", "dill"],
        "avoid_near": ["tomato", "strawberry", "pepper"],
    },
    {
        "wiki_title": "Cauliflower",
        "common_name": "Cauliflower",
        "scientific_name": "Brassica oleracea var. botrytis",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Difficult",
        "description": "Demands steady cool weather and consistent watering. Tie outer leaves over the head to blanch white varieties.",
        "harvest_days_min": 55,
        "harvest_days_max": 90,
        "companions": ["onion", "garlic", "celery", "chamomile", "dill"],
        "avoid_near": ["tomato", "strawberry", "pepper"],
    },
    {
        "wiki_title": "Cabbage",
        "common_name": "Cabbage",
        "scientific_name": "Brassica oleracea var. capitata",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "Heavy-feeding cool-season crop that forms a dense head. Keep soil evenly moist to prevent heads from splitting.",
        "harvest_days_min": 70,
        "harvest_days_max": 120,
        "companions": ["onion", "garlic", "dill", "celery", "chamomile"],
        "avoid_near": ["tomato", "strawberry", "pea"],
    },
    {
        "wiki_title": "Brussels_sprout",
        "common_name": "Brussels Sprouts",
        "scientific_name": "Brassica oleracea var. gemmifera",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Slow",
        "care_level": "Moderate",
        "description": "Long-season crop that forms sprouts along a tall stem. Flavor improves dramatically after the first frost.",
        "harvest_days_min": 80,
        "harvest_days_max": 100,
        "companions": ["onion", "garlic", "thyme", "mint"],
        "avoid_near": ["tomato", "strawberry"],
    },

    # ---------------- Legumes ----------------
    {
        "wiki_title": "Pea",
        "common_name": "Pea",
        "scientific_name": "Pisum sativum",
        "family": "Fabaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Cool-season nitrogen-fixing legume. Plant early in spring; provide support for climbing varieties.",
        "harvest_days_min": 60,
        "harvest_days_max": 70,
        "companions": ["carrot", "cucumber", "corn", "radish", "turnip", "bean"],
        "avoid_near": ["onion", "garlic", "chive", "leek"],
    },
    {
        "wiki_title": "Green_bean",
        "common_name": "Green Bean",
        "scientific_name": "Phaseolus vulgaris",
        "family": "Fabaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Warm-season legume available in bush and pole forms. Fixes nitrogen into soil, making it a great rotation crop.",
        "harvest_days_min": 50,
        "harvest_days_max": 65,
        "companions": ["corn", "cucumber", "radish", "strawberry", "potato", "carrot"],
        "avoid_near": ["onion", "garlic", "fennel"],
    },
    {
        "wiki_title": "Vicia_faba",
        "common_name": "Broad Bean",
        "scientific_name": "Vicia faba",
        "family": "Fabaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Hardy legume that thrives in cool weather. Plant in autumn in mild climates or early spring elsewhere for an early summer harvest.",
        "harvest_days_min": 75,
        "harvest_days_max": 90,
        "companions": ["carrot", "celery", "corn", "cucumber", "potato"],
        "avoid_near": ["onion", "garlic"],
    },

    # ---------------- Roots & tubers ----------------
    {
        "wiki_title": "Carrot",
        "common_name": "Carrot",
        "scientific_name": "Daucus carota",
        "family": "Apiaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Taproot crop that needs loose, stone-free soil to grow straight. Thin seedlings early for well-sized roots.",
        "harvest_days_min": 60,
        "harvest_days_max": 80,
        "companions": ["onion", "leek", "chive", "rosemary", "sage", "tomato", "pea"],
        "avoid_near": ["dill", "parsnip", "celery"],
    },
    {
        "wiki_title": "Radish",
        "common_name": "Radish",
        "scientific_name": "Raphanus sativus",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Fastest root crop — ready in under a month. Great for interplanting with slower crops to break up the soil.",
        "harvest_days_min": 25,
        "harvest_days_max": 35,
        "companions": ["lettuce", "pea", "cucumber", "nasturtium", "spinach"],
        "avoid_near": ["hyssop"],
    },
    {
        "wiki_title": "Beetroot",
        "common_name": "Beet",
        "scientific_name": "Beta vulgaris",
        "family": "Amaranthaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Dual-purpose crop grown for both root and leaves. Thin to 10 cm spacing; the thinnings are edible as microgreens.",
        "harvest_days_min": 55,
        "harvest_days_max": 70,
        "companions": ["onion", "garlic", "broccoli", "lettuce"],
        "avoid_near": ["pole bean"],
    },
    {
        "wiki_title": "Turnip",
        "common_name": "Turnip",
        "scientific_name": "Brassica rapa",
        "family": "Brassicaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Cool-season root vegetable with edible tops. Best harvested small (5-8 cm) when flavor is mild and sweet.",
        "harvest_days_min": 40,
        "harvest_days_max": 60,
        "companions": ["pea", "onion"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Parsnip",
        "common_name": "Parsnip",
        "scientific_name": "Pastinaca sativa",
        "family": "Apiaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["2", "3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Slow",
        "care_level": "Moderate",
        "description": "Long-season root crop that tastes sweeter after frost. Seeds are slow to germinate — keep soil moist for 3 weeks.",
        "harvest_days_min": 100,
        "harvest_days_max": 120,
        "companions": ["pepper", "tomato", "bean", "radish"],
        "avoid_near": ["carrot", "celery"],
    },
    {
        "wiki_title": "Sweet_potato",
        "common_name": "Sweet Potato",
        "scientific_name": "Ipomoea batatas",
        "family": "Convolvulaceae",
        "plant_type": "vegetable",
        "cycle": "perennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Moderate",
        "description": "Heat-loving vining tuber grown from slips. Requires a long warm season; harvest before first frost.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["bush bean", "dill", "thyme"],
        "avoid_near": ["squash"],
    },
    {
        "wiki_title": "Potato",
        "common_name": "Potato",
        "scientific_name": "Solanum tuberosum",
        "family": "Solanaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Grown from seed potatoes. Mound soil around stems as they grow to increase yield and keep tubers out of the light.",
        "harvest_days_min": 70,
        "harvest_days_max": 120,
        "companions": ["bean", "corn", "cabbage", "marigold", "horseradish"],
        "avoid_near": ["tomato", "cucumber", "squash", "pepper", "sunflower"],
    },

    # ---------------- Alliums ----------------
    {
        "wiki_title": "Garlic",
        "common_name": "Garlic",
        "scientific_name": "Allium sativum",
        "family": "Amaryllidaceae",
        "plant_type": "vegetable",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Slow",
        "care_level": "Easy",
        "description": "Plant individual cloves in autumn for harvest the following summer. Snip scapes in late spring to direct energy into bulbs.",
        "harvest_days_min": 90,
        "harvest_days_max": 240,
        "companions": ["tomato", "carrot", "cucumber", "strawberry"],
        "avoid_near": ["bean", "pea", "asparagus"],
    },
    {
        "wiki_title": "Onion",
        "common_name": "Onion",
        "scientific_name": "Allium cepa",
        "family": "Amaryllidaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Grown from sets, seeds, or transplants. Choose a day-length-appropriate variety: short-day for the south, long-day for the north.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["tomato", "carrot", "beet", "lettuce", "strawberry"],
        "avoid_near": ["bean", "pea", "asparagus"],
    },
    {
        "wiki_title": "Leek",
        "common_name": "Leek",
        "scientific_name": "Allium ampeloprasum",
        "family": "Amaryllidaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Slow",
        "care_level": "Moderate",
        "description": "Mild-flavored allium with a long white shank. Hill soil around the stems as they grow to blanch the base.",
        "harvest_days_min": 100,
        "harvest_days_max": 140,
        "companions": ["carrot", "celery", "onion"],
        "avoid_near": ["bean", "pea"],
    },
    {
        "wiki_title": "Shallot",
        "common_name": "Shallot",
        "scientific_name": "Allium ascalonicum",
        "family": "Amaryllidaceae",
        "plant_type": "vegetable",
        "cycle": "biennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Each planted bulb multiplies into a cluster. Plant in autumn or early spring for a summer harvest.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["tomato", "carrot", "lettuce"],
        "avoid_near": ["bean", "pea"],
    },

    # ---------------- Cucurbits & grains ----------------
    {
        "wiki_title": "Maize",
        "common_name": "Corn",
        "scientific_name": "Zea mays",
        "family": "Poaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Frequent",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Moderate",
        "description": "Wind-pollinated — plant in blocks of at least 4x4 for good kernel fill. Heavy feeder that depletes nitrogen.",
        "harvest_days_min": 60,
        "harvest_days_max": 100,
        "companions": ["bean", "cucumber", "pea", "squash", "pumpkin"],
        "avoid_near": ["tomato"],
    },
    {
        "wiki_title": "Pumpkin",
        "common_name": "Pumpkin",
        "scientific_name": "Cucurbita pepo",
        "family": "Cucurbitaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Sprawling vine that needs plenty of room. Harvest when the rind is hard and the stem is dry for long storage.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["corn", "bean", "nasturtium"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Butternut_squash",
        "common_name": "Butternut Squash",
        "scientific_name": "Cucurbita moschata",
        "family": "Cucurbitaceae",
        "plant_type": "vegetable",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Winter squash with sweet, nutty flesh. Cure harvested fruit for 1-2 weeks in a warm dry spot for long storage.",
        "harvest_days_min": 100,
        "harvest_days_max": 120,
        "companions": ["corn", "bean", "radish", "nasturtium"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Watermelon",
        "common_name": "Watermelon",
        "scientific_name": "Citrullus lanatus",
        "family": "Cucurbitaceae",
        "plant_type": "fruit",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Moderate",
        "description": "Needs a long, hot season and plenty of space. Reduce watering as fruit ripens to concentrate sugars.",
        "harvest_days_min": 80,
        "harvest_days_max": 100,
        "companions": ["corn", "radish", "nasturtium"],
        "avoid_near": ["potato"],
    },
    {
        "wiki_title": "Cantaloupe",
        "common_name": "Cantaloupe",
        "scientific_name": "Cucumis melo",
        "family": "Cucurbitaceae",
        "plant_type": "fruit",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Moderate",
        "description": "Sweet netted melon that slips from the vine when ripe. Prefers warm nights and consistent moisture while fruit sets.",
        "harvest_days_min": 70,
        "harvest_days_max": 90,
        "companions": ["corn", "radish", "nasturtium"],
        "avoid_near": ["potato", "cucumber"],
    },

    # ---------------- Herbs (annual) ----------------
    {
        "wiki_title": "Basil",
        "common_name": "Basil",
        "scientific_name": "Ocimum basilicum",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Warm-season culinary herb. Pinch flowers to keep leaves tender and harvest frequently from the top to encourage bushing.",
        "harvest_days_min": 50,
        "harvest_days_max": 75,
        "companions": ["tomato", "pepper", "oregano", "asparagus"],
        "avoid_near": ["rue", "sage"],
    },
    {
        "wiki_title": "Parsley",
        "common_name": "Parsley",
        "scientific_name": "Petroselinum crispum",
        "family": "Apiaceae",
        "plant_type": "herb",
        "cycle": "biennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Biennial grown as an annual for its fresh leaves. Slow to germinate — soak seeds overnight to speed things up.",
        "harvest_days_min": 70,
        "harvest_days_max": 90,
        "companions": ["tomato", "carrot", "corn"],
        "avoid_near": ["lettuce", "mint"],
    },
    {
        "wiki_title": "Coriander",
        "common_name": "Cilantro",
        "scientific_name": "Coriandrum sativum",
        "family": "Apiaceae",
        "plant_type": "herb",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Cool-season herb that bolts in summer heat. Sow every 3 weeks for continuous leaves, or let plants flower for coriander seed.",
        "harvest_days_min": 45,
        "harvest_days_max": 70,
        "companions": ["spinach", "tomato", "dill"],
        "avoid_near": ["fennel"],
    },
    {
        "wiki_title": "Dill",
        "common_name": "Dill",
        "scientific_name": "Anethum graveolens",
        "family": "Apiaceae",
        "plant_type": "herb",
        "cycle": "annual",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Feathery culinary herb that attracts beneficial insects. Self-seeds readily once allowed to flower.",
        "harvest_days_min": 40,
        "harvest_days_max": 60,
        "companions": ["cabbage", "cucumber", "corn", "lettuce", "onion"],
        "avoid_near": ["carrot", "tomato"],
    },
    {
        "wiki_title": "Matricaria_chamomilla",
        "common_name": "Chamomile",
        "scientific_name": "Matricaria chamomilla",
        "family": "Asteraceae",
        "plant_type": "herb",
        "cycle": "annual",
        "watering": "Minimum",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Daisy-like flowers used for calming tea. Drought-tolerant once established; self-seeds generously.",
        "harvest_days_min": 60,
        "harvest_days_max": 65,
        "companions": ["cabbage", "cucumber", "onion"],
        "avoid_near": ["mint"],
    },

    # ---------------- Herbs (perennial) ----------------
    {
        "wiki_title": "Chives",
        "common_name": "Chive",
        "scientific_name": "Allium schoenoprasum",
        "family": "Amaryllidaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Clump-forming perennial with edible purple flowers. Divide every 3-4 years to keep clumps vigorous.",
        "harvest_days_min": 60,
        "harvest_days_max": 90,
        "companions": ["carrot", "tomato", "rose"],
        "avoid_near": ["bean", "pea"],
    },
    {
        "wiki_title": "Rosemary",
        "common_name": "Rosemary",
        "scientific_name": "Salvia rosmarinus",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["7", "8", "9", "10", "11"],
        "growth_rate": "Slow",
        "care_level": "Easy",
        "description": "Mediterranean evergreen shrub. Needs sharp drainage; overwater to kill it. Bring pots indoors in cold climates.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["bean", "cabbage", "carrot", "sage"],
        "avoid_near": ["tomato"],
    },
    {
        "wiki_title": "Thyme",
        "common_name": "Thyme",
        "scientific_name": "Thymus vulgaris",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Slow",
        "care_level": "Easy",
        "description": "Low-growing Mediterranean herb thriving in poor, well-drained soil. Trim lightly after flowering to prevent woodiness.",
        "harvest_days_min": 75,
        "harvest_days_max": 90,
        "companions": ["cabbage", "eggplant", "potato", "tomato"],
        "avoid_near": [],
    },
    {
        "wiki_title": "Oregano",
        "common_name": "Oregano",
        "scientific_name": "Origanum vulgare",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Hardy Mediterranean herb with the strongest flavor just before flowering. Trim often to prevent legginess.",
        "harvest_days_min": 80,
        "harvest_days_max": 90,
        "companions": ["pepper", "tomato", "squash", "bean"],
        "avoid_near": [],
    },
    {
        "wiki_title": "Salvia_officinalis",
        "common_name": "Sage",
        "scientific_name": "Salvia officinalis",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Woody perennial with silvery aromatic leaves. Replace plants every 4-5 years as they become woody and less productive.",
        "harvest_days_min": 75,
        "harvest_days_max": 90,
        "companions": ["carrot", "cabbage", "rosemary", "strawberry"],
        "avoid_near": ["cucumber", "onion"],
    },
    {
        "wiki_title": "Mentha",
        "common_name": "Mint",
        "scientific_name": "Mentha",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Frequent",
        "sunlight": ["full sun", "part sun", "part shade"],
        "hardiness_zones": ["3", "4", "5", "6", "7", "8", "9", "10", "11"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Aggressive spreader — grow in a container or dedicated bed. Pinch flowers to keep leaves full-flavored.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["cabbage", "tomato"],
        "avoid_near": ["parsley", "chamomile"],
    },
    {
        "wiki_title": "Lavandula",
        "common_name": "Lavender",
        "scientific_name": "Lavandula",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun"],
        "hardiness_zones": ["5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Aromatic shrub that loves lean alkaline soil and sharp drainage. Harvest spikes when lower buds just begin to open.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["tomato", "cabbage", "oregano"],
        "avoid_near": ["mint"],
    },
    {
        "wiki_title": "Lemon_balm",
        "common_name": "Lemon Balm",
        "scientific_name": "Melissa officinalis",
        "family": "Lamiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Average",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9"],
        "growth_rate": "Fast",
        "care_level": "Easy",
        "description": "Lemon-scented mint relative. Cut back hard after flowering for a fresh flush of tender leaves.",
        "harvest_days_min": 70,
        "harvest_days_max": 90,
        "companions": ["tomato", "squash", "broccoli"],
        "avoid_near": [],
    },
    {
        "wiki_title": "Tarragon",
        "common_name": "Tarragon",
        "scientific_name": "Artemisia dracunculus",
        "family": "Asteraceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Minimum",
        "sunlight": ["full sun", "part sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9"],
        "growth_rate": "Medium",
        "care_level": "Moderate",
        "description": "French tarragon is grown from divisions, not seed. Aniseed flavor is strongest on mature plants harvested in summer.",
        "harvest_days_min": 90,
        "harvest_days_max": 120,
        "companions": ["eggplant", "tomato"],
        "avoid_near": [],
    },
    {
        "wiki_title": "Fennel",
        "common_name": "Fennel",
        "scientific_name": "Foeniculum vulgare",
        "family": "Apiaceae",
        "plant_type": "herb",
        "cycle": "perennial",
        "watering": "Average",
        "sunlight": ["full sun"],
        "hardiness_zones": ["4", "5", "6", "7", "8", "9", "10"],
        "growth_rate": "Medium",
        "care_level": "Easy",
        "description": "Anise-flavored herb with edible bulb, fronds, and seeds. Plant well away from other vegetables — it inhibits their growth.",
        "harvest_days_min": 90,
        "harvest_days_max": 115,
        "companions": [],
        "avoid_near": ["tomato", "bean", "pepper", "cabbage", "coriander"],
    },
]
